# """
# Django settings for FutbolVagos project.

# Generated by 'django-admin startproject' using Django 5.0.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.0/ref/settings/
# """

# from pathlib import Path
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-2sxi+um0x*pixm%4n2-t-q)36kqg8gmpd=r507%ci=3+52b&rs'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'core',  
#     'rest_framework',
#     'drf_yasg',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',  
#     'keycloak_oidc.middleware.OIDCMiddleware',  
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'FutbolVagos.middleware.KeycloakMiddleware',
# ]

# ROOT_URLCONF = 'FutbolVagos.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'FutbolVagos.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'futbolvagosdb',
# #         'USER': 'admin',
# #         'PASSWORD': '123',
# #         'HOST': 'localhost',
# #         'PORT': '5432', 
# #     }
# # }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'futbolvagosdb'),
#         'USER': os.getenv('DB_USER', 'admin'),
#         'PASSWORD': os.getenv('DB_PASSWORD', '123'),
#         'HOST': os.getenv('DB_HOST', 'db'),  # Aquí cambiamos 'localhost' por 'db'
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }
# }

# print("DB_NAME:", os.getenv('DB_NAME'))
# print("DB_USER:", os.getenv('DB_USER'))
# print("DB_PASSWORD:", os.getenv('DB_PASSWORD'))
# print("DB_HOST:", os.getenv('DB_HOST'))
# print("DB_PORT:", os.getenv('DB_PORT'))

# # Password validation
# # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# KEYCLOAK_CONFIG = {
#     "SERVER_URL": "http://localhost:8080",  # Cambia localhost por keycloak
#     "REALM": "futbolvagos",
#     "CLIENT_ID": "django-backend",
# }

# KEYCLOAK_PUBLIC_KEY = """
# -----BEGIN PUBLIC KEY-----
# MIICpTCCAY0CBgGWmTx70jANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAtmdXRib2x2YWdvczAeFw0yNTA1MDQwMjU4MjBaFw0zNTA1MDQwMzAwMDBaMBYxFDASBgNVBAMMC2Z1dGJvbHZhZ29zMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6HU5CYpwfVPvod3pGgaR14Os9/eEmsKNPyQ2htDHcEAtpYiHnxEYbdrxmZmo+PM38CH7v0VfjUvXQD8L/dAYu/mi3/z12sTYAVTnEXAwW7UnYTFHllDxRruBNa3VTYvuk9OibD3z55/L7AoLIxSKHzrb7mmO8ZURtqa3PJecD0GRVbg8CTrGWFloJvX/qK9kPQwpPFiVLMJFCMDT3be2/btR1rECyJrNslyJ/YbaPMYmE0d2NY4kccGntJPjf4QYc2uW6riEiYQSTHzE6xHciMY3TsfgFt3C5AwLxwyQJ2GtRL4NlU/7PMBo4k9bNQtE4UwRYbvlC5tXJWRGyFrUyQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBQpoFis9oI38HfccVuNmu9SySloCpLZczObi6JWFkCAtmV51UIhl/Yx0XairtJ+D7L0ESkZBeExbhzJUUAx57P94/q92QlvRvOytdW5i7ZbkXxGHPLPc2eM6EX5JtTkQY7LzM7XrASCa7Qs4Oc29kSGbDSX/o8K5rC5OH5LEhlv6Mql59mnPSFP6nLUME4lzFmNAzav+PAlV2XOyxMdprFTNyG2CGpK1wE8JYvTv9UQsjMoV+SJs0kUJi1qtgrN9nvs09XKPBw14AW4sG3yKxchXTKx5c3z9/c1/HVvoX06ck73md40neztkPVmy9onDLXhKIl4cK7qroB6fd57/G3
# -----END PUBLIC KEY-----
# """
# REST_FRAMEWORK = {  
#     'DEFAULT_AUTHENTICATION_CLASSES': [  
#         'myapp.authentication.KeycloakAuthentication',  
#     ],  
# }
"""
Django settings for FutbolVagos project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2sxi+um0x*pixm%4n2-t-q)36kqg8gmpd=r507%ci=3+52b&rs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  
    'rest_framework',
    'drf_yasg',
]

 
KEYCLOAK_SERVER_URL = 'http://localhost:8000/auth'  
KEYCLOAK_REALM = 'futbolvagos'  
KEYCLOAK_CLIENT_ID = 'django-backend'  
KEYCLOAK_CLIENT_SECRET = 'nC4IyRKlU1bSFPViJ9v3nKv0JwEVn2P2'

AUTHENTICATION_BACKENDS = [  
    'myapp.keycloak_backend.KeycloakBackend',  
    'django.contrib.auth.backends.ModelBackend',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'keycloak_oidc.middleware.OIDCMiddleware', 
]

ROOT_URLCONF = 'FutbolVagos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FutbolVagos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'futbolvagosdb',
#         'USER': 'admin',
#         'PASSWORD': '123',
#         'HOST': 'localhost',
#         'PORT': '5432', 
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'futbolvagosdb'),
        'USER': os.getenv('DB_USER', 'admin'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123'),
        'HOST': os.getenv('DB_HOST', 'db'),  # Aquí cambiamos 'localhost' por 'db'
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'