# Generated by Django 5.1.7 on 2025-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Mantenimiento', 'Mantenimiento'), ('Recepcionista', 'Recepcionista'), ('Vigilante', 'Vigilante')], max_length=100),
        ),
    ]
