# Generated by Django 5.1.7 on 2025-03-31 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trabajador_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='horario',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
