# Generated by Django 5.1.7 on 2025-03-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_reservacion_horario_reservacion_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='fecha_reserva',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
