# Generated by Django 5.1.7 on 2025-03-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_fecha_reserva_reservacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
