# Generated by Django 5.1.7 on 2025-03-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reservacion_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
